//HintName: GenericUnionTypeAttribute.g.cs
// <auto-generated>
//   This code was generated by https://github.com/Ne4to/N.SourceGenerators.UnionTypes
//   Feel free to open an issue
// </auto-generated>
#if NETCOREAPP3_1_OR_GREATER
#nullable enable
#endif
using Attribute = global::System.Attribute;
using AttributeUsageAttribute = global::System.AttributeUsageAttribute;
using AttributeTargets = global::System.AttributeTargets;

namespace N.SourceGenerators.UnionTypes
{
    [AttributeUsageAttribute(AttributeTargets.GenericParameter, Inherited = false, AllowMultiple = false)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class GenericUnionTypeAttribute : Attribute
    {
#if NETCOREAPP3_1_OR_GREATER
        public string? Alias { get; set; }
        public bool AllowNull { get; set; }
        public object? TypeDiscriminator { get; set; }
#else
        public string Alias { get; set; }
        public bool AllowNull { get; set; }
        public object TypeDiscriminator { get; set; }
#endif
    }
}