//HintName: JsonPolymorphicUnionAttribute.g.cs
// <auto-generated>
//   This code was generated by https://github.com/Ne4to/N.SourceGenerators.UnionTypes
//   Feel free to open an issue
// </auto-generated>
#if NETCOREAPP3_1_OR_GREATER
#nullable enable
#endif
using Attribute = global::System.Attribute;
using AttributeUsageAttribute = global::System.AttributeUsageAttribute;
using AttributeTargets = global::System.AttributeTargets;

namespace N.SourceGenerators.UnionTypes
{
    [AttributeUsageAttribute(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class JsonPolymorphicUnionAttribute : Attribute
    {
#if NETCOREAPP3_1_OR_GREATER
        public string? TypeDiscriminatorPropertyName { get; set; }
#else
        public string TypeDiscriminatorPropertyName { get; set; }
#endif    
    }
}