//HintName: Result.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
partial class Result
{
    private readonly Success? _Success;
    public bool IsSuccess => _Success != null;
    public Success AsSuccess => _Success ?? throw new System.InvalidOperationException("This is not a Success");
    public Result(Success Success)
    {
        System.ArgumentNullException.ThrowIfNull(Success);
        _Success = Success;
    }

    public static implicit operator Result(Success Success) => new Result(Success);
    private readonly Error? _Error;
    public bool IsError => _Error != null;
    public Error AsError => _Error ?? throw new System.InvalidOperationException("This is not a Error");
    public Result(Error Error)
    {
        System.ArgumentNullException.ThrowIfNull(Error);
        _Error = Error;
    }

    public static implicit operator Result(Error Error) => new Result(Error);
}