//HintName: Result.g.cs
// <auto-generated>
//   This code was generated by https://github.com/Ne4to/N.SourceGenerators.UnionTypes
//   Feel free to open an issue
// </auto-generated>
#pragma warning disable
#nullable enable
namespace MyApp
{
    partial class Result : System.IEquatable<Result>
    {
        private readonly global::MyApp.Success? _success;
        public bool IsSuccess => _success != null;
        public global::MyApp.Success AsSuccess => _success ?? throw new System.InvalidOperationException("Inner value is not Success");
        public Result(global::MyApp.Success success)
        {
            System.ArgumentNullException.ThrowIfNull(success);
            _success = success;
        }

        public static implicit operator Result(global::MyApp.Success success) => new Result(success);
        public static explicit operator global::MyApp.Success(Result value) => value._success ?? throw new System.InvalidOperationException("Inner value is not Success");
        public bool TryGetSuccess([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::MyApp.Success? value)
        {
            if (_success != null)
            {
                value = _success;
                return true;
            }
            else
            {
                value = default;
                return false;
            }
        }

        private readonly global::MyApp.Error? _error;
        public bool IsError => _error != null;
        public global::MyApp.Error AsError => _error ?? throw new System.InvalidOperationException("Inner value is not Error");
        public Result(global::MyApp.Error @error)
        {
            System.ArgumentNullException.ThrowIfNull(@error);
            _error = @error;
        }

        public static implicit operator Result(global::MyApp.Error @error) => new Result(@error);
        public static explicit operator global::MyApp.Error(Result value) => value._error ?? throw new System.InvalidOperationException("Inner value is not Error");
        public bool TryGetError([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::MyApp.Error? value)
        {
            if (_error != null)
            {
                value = _error;
                return true;
            }
            else
            {
                value = default;
                return false;
            }
        }

        private readonly global::System.Collections.Generic.IReadOnlyList<int>? _iReadOnlyListOfInt32;
        public bool IsIReadOnlyListOfInt32 => _iReadOnlyListOfInt32 != null;
        public global::System.Collections.Generic.IReadOnlyList<int> AsIReadOnlyListOfInt32 => _iReadOnlyListOfInt32 ?? throw new System.InvalidOperationException("Inner value is not IReadOnlyListOfInt32");
        public Result(global::System.Collections.Generic.IReadOnlyList<int> iReadOnlyListOfInt32)
        {
            System.ArgumentNullException.ThrowIfNull(iReadOnlyListOfInt32);
            _iReadOnlyListOfInt32 = iReadOnlyListOfInt32;
        }

        public bool TryGetIReadOnlyListOfInt32([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::System.Collections.Generic.IReadOnlyList<int>? value)
        {
            if (_iReadOnlyListOfInt32 != null)
            {
                value = _iReadOnlyListOfInt32;
                return true;
            }
            else
            {
                value = default;
                return false;
            }
        }

        private readonly string[]? _arrayOfString;
        public bool IsArrayOfString => _arrayOfString != null;
        public string[] AsArrayOfString => _arrayOfString ?? throw new System.InvalidOperationException("Inner value is not ArrayOfString");
        public Result(string[] arrayOfString)
        {
            System.ArgumentNullException.ThrowIfNull(arrayOfString);
            _arrayOfString = arrayOfString;
        }

        public static implicit operator Result(string[] arrayOfString) => new Result(arrayOfString);
        public static explicit operator string[](Result value) => value._arrayOfString ?? throw new System.InvalidOperationException("Inner value is not ArrayOfString");
        public bool TryGetArrayOfString([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string[]? value)
        {
            if (_arrayOfString != null)
            {
                value = _arrayOfString;
                return true;
            }
            else
            {
                value = default;
                return false;
            }
        }

        private readonly global::System.Tuple<int, string>? _tupleOfInt32AndString;
        public bool IsTupleOfInt32AndString => _tupleOfInt32AndString != null;
        public global::System.Tuple<int, string> AsTupleOfInt32AndString => _tupleOfInt32AndString ?? throw new System.InvalidOperationException("Inner value is not TupleOfInt32AndString");
        public Result(global::System.Tuple<int, string> tupleOfInt32AndString)
        {
            System.ArgumentNullException.ThrowIfNull(tupleOfInt32AndString);
            _tupleOfInt32AndString = tupleOfInt32AndString;
        }

        public static implicit operator Result(global::System.Tuple<int, string> tupleOfInt32AndString) => new Result(tupleOfInt32AndString);
        public static explicit operator global::System.Tuple<int, string>(Result value) => value._tupleOfInt32AndString ?? throw new System.InvalidOperationException("Inner value is not TupleOfInt32AndString");
        public bool TryGetTupleOfInt32AndString([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::System.Tuple<int, string>? value)
        {
            if (_tupleOfInt32AndString != null)
            {
                value = _tupleOfInt32AndString;
                return true;
            }
            else
            {
                value = default;
                return false;
            }
        }

        public TOut Match<TOut>(global::System.Func<global::MyApp.Success, TOut> matchSuccess, global::System.Func<global::MyApp.Error, TOut> matchError, global::System.Func<global::System.Collections.Generic.IReadOnlyList<int>, TOut> matchIReadOnlyListOfInt32, global::System.Func<string[], TOut> matchArrayOfString, global::System.Func<global::System.Tuple<int, string>, TOut> matchTupleOfInt32AndString)
        {
            if (_success != null)
                return matchSuccess(_success!);
            if (_error != null)
                return matchError(_error!);
            if (_iReadOnlyListOfInt32 != null)
                return matchIReadOnlyListOfInt32(_iReadOnlyListOfInt32!);
            if (_arrayOfString != null)
                return matchArrayOfString(_arrayOfString!);
            if (_tupleOfInt32AndString != null)
                return matchTupleOfInt32AndString(_tupleOfInt32AndString!);
            throw new System.InvalidOperationException("Inner type is unknown");
        }

        public async global::System.Threading.Tasks.Task<TOut> MatchAsync<TOut>(global::System.Func<global::MyApp.Success, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<TOut>> matchSuccess, global::System.Func<global::MyApp.Error, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<TOut>> matchError, global::System.Func<global::System.Collections.Generic.IReadOnlyList<int>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<TOut>> matchIReadOnlyListOfInt32, global::System.Func<string[], global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<TOut>> matchArrayOfString, global::System.Func<global::System.Tuple<int, string>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<TOut>> matchTupleOfInt32AndString, global::System.Threading.CancellationToken ct)
        {
            if (_success != null)
                return await matchSuccess(_success!, ct).ConfigureAwait(false);
            if (_error != null)
                return await matchError(_error!, ct).ConfigureAwait(false);
            if (_iReadOnlyListOfInt32 != null)
                return await matchIReadOnlyListOfInt32(_iReadOnlyListOfInt32!, ct).ConfigureAwait(false);
            if (_arrayOfString != null)
                return await matchArrayOfString(_arrayOfString!, ct).ConfigureAwait(false);
            if (_tupleOfInt32AndString != null)
                return await matchTupleOfInt32AndString(_tupleOfInt32AndString!, ct).ConfigureAwait(false);
            throw new System.InvalidOperationException("Inner type is unknown");
        }

        public void Switch(global::System.Action<global::MyApp.Success> switchSuccess, global::System.Action<global::MyApp.Error> switchError, global::System.Action<global::System.Collections.Generic.IReadOnlyList<int>> switchIReadOnlyListOfInt32, global::System.Action<string[]> switchArrayOfString, global::System.Action<global::System.Tuple<int, string>> switchTupleOfInt32AndString)
        {
            if (_success != null)
            {
                switchSuccess(_success!);
                return;
            }

            if (_error != null)
            {
                switchError(_error!);
                return;
            }

            if (_iReadOnlyListOfInt32 != null)
            {
                switchIReadOnlyListOfInt32(_iReadOnlyListOfInt32!);
                return;
            }

            if (_arrayOfString != null)
            {
                switchArrayOfString(_arrayOfString!);
                return;
            }

            if (_tupleOfInt32AndString != null)
            {
                switchTupleOfInt32AndString(_tupleOfInt32AndString!);
                return;
            }

            throw new System.InvalidOperationException("Inner type is unknown");
        }

        public async global::System.Threading.Tasks.Task SwitchAsync(global::System.Func<global::MyApp.Success, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> switchSuccess, global::System.Func<global::MyApp.Error, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> switchError, global::System.Func<global::System.Collections.Generic.IReadOnlyList<int>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> switchIReadOnlyListOfInt32, global::System.Func<string[], global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> switchArrayOfString, global::System.Func<global::System.Tuple<int, string>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> switchTupleOfInt32AndString, global::System.Threading.CancellationToken ct)
        {
            if (_success != null)
            {
                await switchSuccess(_success!, ct).ConfigureAwait(false);
                return;
            }

            if (_error != null)
            {
                await switchError(_error!, ct).ConfigureAwait(false);
                return;
            }

            if (_iReadOnlyListOfInt32 != null)
            {
                await switchIReadOnlyListOfInt32(_iReadOnlyListOfInt32!, ct).ConfigureAwait(false);
                return;
            }

            if (_arrayOfString != null)
            {
                await switchArrayOfString(_arrayOfString!, ct).ConfigureAwait(false);
                return;
            }

            if (_tupleOfInt32AndString != null)
            {
                await switchTupleOfInt32AndString(_tupleOfInt32AndString!, ct).ConfigureAwait(false);
                return;
            }

            throw new System.InvalidOperationException("Inner type is unknown");
        }

        public global::System.Type ValueType
        {
            get
            {
                if (_success != null)
                    return typeof(global::MyApp.Success);
                if (_error != null)
                    return typeof(global::MyApp.Error);
                if (_iReadOnlyListOfInt32 != null)
                    return typeof(global::System.Collections.Generic.IReadOnlyList<int>);
                if (_arrayOfString != null)
                    return typeof(string[]);
                if (_tupleOfInt32AndString != null)
                    return typeof(global::System.Tuple<int, string>);
                throw new System.InvalidOperationException("Inner type is unknown");
            }
        }

        public override int GetHashCode()
        {
            if (_success != null)
                return _success.GetHashCode();
            if (_error != null)
                return _error.GetHashCode();
            if (_iReadOnlyListOfInt32 != null)
                return _iReadOnlyListOfInt32.GetHashCode();
            if (_arrayOfString != null)
                return _arrayOfString.GetHashCode();
            if (_tupleOfInt32AndString != null)
                return _tupleOfInt32AndString.GetHashCode();
            throw new System.InvalidOperationException("Inner type is unknown");
        }

        public static bool operator ==(Result? left, Result? right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Result? left, Result? right)
        {
            return !Equals(left, right);
        }

        public bool Equals(Result? other)
        {
            if (ReferenceEquals(null, other))
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            if (ValueType != other.ValueType)
            {
                return false;
            }

            if (_success != null)
                return System.Collections.Generic.EqualityComparer<global::MyApp.Success>.Default.Equals(_success!, other._success);
            if (_error != null)
                return System.Collections.Generic.EqualityComparer<global::MyApp.Error>.Default.Equals(_error!, other._error);
            if (_iReadOnlyListOfInt32 != null)
                return System.Collections.Generic.EqualityComparer<global::System.Collections.Generic.IReadOnlyList<int>>.Default.Equals(_iReadOnlyListOfInt32!, other._iReadOnlyListOfInt32);
            if (_arrayOfString != null)
                return System.Collections.Generic.EqualityComparer<string[]>.Default.Equals(_arrayOfString!, other._arrayOfString);
            if (_tupleOfInt32AndString != null)
                return System.Collections.Generic.EqualityComparer<global::System.Tuple<int, string>>.Default.Equals(_tupleOfInt32AndString!, other._tupleOfInt32AndString);
            throw new System.InvalidOperationException("Inner type is unknown");
        }

        public override string ToString()
        {
            if (_success != null)
                return _success.ToString();
            if (_error != null)
                return _error.ToString();
            if (_iReadOnlyListOfInt32 != null)
                return _iReadOnlyListOfInt32.ToString();
            if (_arrayOfString != null)
                return _arrayOfString.ToString();
            if (_tupleOfInt32AndString != null)
                return _tupleOfInt32AndString.ToString();
            throw new System.InvalidOperationException("Inner type is unknown");
        }

        public override bool Equals(object? other)
        {
            if (ReferenceEquals(null, other))
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            if (other.GetType() != typeof(Result))
            {
                return false;
            }

            return Equals((Result)other);
        }
    }
}