//HintName: UnionTypeAttribute.g.cs
// <auto-generated>
//   This code was generated by https://github.com/Ne4to/N.SourceGenerators.UnionTypes
//   Feel free to open an issue
// </auto-generated>
#if NETCOREAPP3_1_OR_GREATER
#nullable enable
#endif
using Attribute = global::System.Attribute;
using AttributeUsageAttribute = global::System.AttributeUsageAttribute;
using AttributeTargets = global::System.AttributeTargets;
using Type = global::System.Type;
using CallerLineNumber = System.Runtime.CompilerServices.CallerLineNumberAttribute;

namespace N.SourceGenerators.UnionTypes
{
    [AttributeUsageAttribute(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class UnionTypeAttribute : Attribute
    {
        public Type Type { get; }
#if NETCOREAPP3_1_OR_GREATER
        public string? Alias { get; }
#else
        public string Alias { get; }
#endif
        public int Order { get; }
        public bool AllowNull { get; set; }
#if NETCOREAPP3_1_OR_GREATER
        public object? TypeDiscriminator { get; set; }
#else
        public object TypeDiscriminator { get; set; }
#endif

#if NETCOREAPP3_1_OR_GREATER
        public UnionTypeAttribute(Type type, string? alias = null, [CallerLineNumber] int order = 0)
#else
        public UnionTypeAttribute(Type type, string alias = null, [CallerLineNumber] int order = 0)
#endif
        {
            Type = type;
            Alias = alias;
            Order = order;
        }
    }
}