//HintName: JsonTestsUnionJsonConverter.g.cs
// <auto-generated>
//   This code was generated by https://github.com/Ne4to/N.SourceGenerators.UnionTypes
//   Feel free to open an issue
// </auto-generated>
#pragma warning disable
#nullable enable
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal class JsonTestsUnionJsonConverter : System.Text.Json.Serialization.JsonConverter<JsonTestsUnion>
{
    private static object? GetDiscriminator(object x)
    {
        if (x is global::JsonTestsFooJ)
        {
            return "Foo";
        }

        if (x is global::JsonTestsBarJ)
        {
            return "Bar";
        }

        throw new System.ArgumentOutOfRangeException(nameof(x), x, $"{x.GetType()} has no discriminator specified in {typeof(global::JsonTestsUnion)}");
    }

    private static void AddDiscriminatorModifier(System.Text.Json.Serialization.Metadata.JsonTypeInfo jsonTypeInfo)
    {
        if (jsonTypeInfo.Kind != System.Text.Json.Serialization.Metadata.JsonTypeInfoKind.Object)
            return;
        System.Text.Json.Serialization.Metadata.JsonPropertyInfo jsonPropertyInfo = jsonTypeInfo.CreateJsonPropertyInfo(typeof(string), "$type");
        jsonPropertyInfo.Get = GetDiscriminator;
        jsonTypeInfo.Properties.Insert(0, jsonPropertyInfo);
    }

    private static System.Type GetSubType(ref System.Text.Json.Utf8JsonReader reader)
    {
        if (reader.TokenType != System.Text.Json.JsonTokenType.String)
        {
            throw new System.Text.Json.JsonException($"Expected string discriminator value, got {reader.TokenType}");
        }

        if (reader.ValueTextEquals("Foo"u8))
        {
            return typeof(global::JsonTestsFooJ);
        }

        if (reader.ValueTextEquals("Bar"u8))
        {
            return typeof(global::JsonTestsBarJ);
        }

        throw new System.Text.Json.JsonException($"{reader.GetString()} is not a valid discriminator value");
    }

    public override global::JsonTestsUnion Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
    {
        System.Text.Json.JsonEncodedText discriminatorPropertyName = System.Text.Json.JsonEncodedText.Encode("$type");
        var nestedReader = reader;
        if (nestedReader.TokenType == System.Text.Json.JsonTokenType.None)
        {
            nestedReader.Read();
        }

        while (nestedReader.Read())
        {
            if (nestedReader.TokenType == System.Text.Json.JsonTokenType.PropertyName && nestedReader.ValueTextEquals(discriminatorPropertyName.EncodedUtf8Bytes))
            {
                nestedReader.Read();
                var subType = GetSubType(ref nestedReader);
                var result = System.Text.Json.JsonSerializer.Deserialize(ref reader, subType, options);
                if (result is global::JsonTestsFooJ jsonTestsFooJ)
                {
                    return new global::JsonTestsUnion(jsonTestsFooJ);
                }

                if (result is global::JsonTestsBarJ jsonTestsBarJ)
                {
                    return new global::JsonTestsUnion(jsonTestsBarJ);
                }

                throw new System.InvalidOperationException("Unable to deserialize to JsonTestsUnion");
            }
            else if (nestedReader.TokenType == System.Text.Json.JsonTokenType.StartObject || nestedReader.TokenType == System.Text.Json.JsonTokenType.StartArray)
            {
                if (!nestedReader.TrySkip())
                {
                    return default !;
                }
            }
            else if (nestedReader.TokenType == System.Text.Json.JsonTokenType.EndObject)
            {
                break;
            }
        }

        if (reader.IsFinalBlock)
        {
            throw new System.Text.Json.JsonException($"Unable to find discriminator property $type");
        }

        return default !;
    }

    public override void Write(System.Text.Json.Utf8JsonWriter writer, global::JsonTestsUnion value, System.Text.Json.JsonSerializerOptions options)
    {
        var customOptions = new System.Text.Json.JsonSerializerOptions(options)
        {TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver{Modifiers = {AddDiscriminatorModifier}}};
        value.Switch(x => System.Text.Json.JsonSerializer.Serialize(writer, x, customOptions), x => System.Text.Json.JsonSerializer.Serialize(writer, x, customOptions));
    }
}