//HintName: JsonTestsUnionJsonConverterAttribute.g.cs
// <auto-generated>
//   This code was generated by https://github.com/Ne4to/N.SourceGenerators.UnionTypes
//   Feel free to open an issue
// </auto-generated>
#pragma warning disable
#nullable enable
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal class JsonTestsUnionJsonConverterAttribute : System.Text.Json.Serialization.JsonConverterAttribute
{
    public override System.Text.Json.Serialization.JsonConverter? CreateConverter(System.Type typeToConvert)
    {
        return new JsonTestsUnionJsonConverter();
    }
}