//HintName: BusinessLogicModelFromConverter.g.cs
// <auto-generated>
//   This code was generated by https://github.com/Ne4to/N.SourceGenerators.UnionTypes
//   Feel free to open an issue
// </auto-generated>
#pragma warning disable
#nullable enable
namespace BusinessLogic
{
    partial class BusinessLogicModel
    {
        public static implicit operator BusinessLogicModel(global::DataAccess.DataAccessModel value)
        {
            return value.Match<BusinessLogicModel>((global::DataAccess.DataAccessModel1 x) => (BusinessLogicModel)new BusinessLogicModel(x), (global::DataAccess.DataAccessModel2 x) => (BusinessLogicModel)new BusinessLogicModel(x));
        }
    }
}